In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [1]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [2]:
np.array(my_mat)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(5,7)

TypeError: data type not understood

In [10]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.00166784, 0.04061947, 0.65190113, 0.918657  , 0.46598811])

In [14]:
np.random.rand(5,5)

array([[0.84567044, 0.88378412, 0.47466305, 0.8057008 , 0.14156496],
       [0.13460929, 0.8819316 , 0.54861907, 0.3934219 , 0.79397898],
       [0.64795992, 0.02079521, 0.35917749, 0.14083001, 0.46501661],
       [0.75525844, 0.54150313, 0.15791902, 0.86420069, 0.66354082],
       [0.81278507, 0.43029405, 0.9785199 , 0.02361023, 0.67740648]])

In [15]:
np.random.randn(3)

array([ 0.4435325 ,  1.91457571, -0.20261587])

In [16]:
np.random.randn(5,5)

array([[ 0.22576326,  0.72717573, -0.49066782, -0.93355841,  0.57512957],
       [ 0.02233085, -0.37292407, -0.72807505, -0.21152152, -0.56749341],
       [ 0.25154332, -1.1837219 ,  0.14782323,  0.76170173, -1.12264373],
       [-2.03707245, -0.17976977,  1.79188791,  0.77053114,  1.0813718 ],
       [ 1.402469  , -0.84599641, -1.20157087,  0.29729631,  0.65568972]])

In [17]:
np.random.randint(1,120,30)

array([ 18,   9,  72,   1, 109,   6, 101,  73,   8,  23,  55,  43, 116,
         5, 115, 111,  26, 100, 118,  81,  13, 110,  28,  11,  96,  66,
        52, 108,  65,  74])

In [18]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,12)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([35, 19,  8, 10,  5, 21, 16,  3, 37, 39, 34, 30])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr.max()

39

In [23]:
ranarr.argmax()

9

In [24]:
ranarr.min()

3

In [25]:
ranarr.argmin()

7

In [26]:
arr.shape

(25,)

In [27]:
arr = arr.reshape(5,5)

In [28]:
arr.shape

(5, 5)

In [29]:
arr.dtype

dtype('int32')

In [30]:
from numpy.random import randint

In [31]:
randint(3,12)

6